[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/discogs/random"
  to = "/.netlify/functions/discogs-random"
  status = 200

[[redirects]]
  from = "/api/youtube/search"
  to = "/.netlify/functions/youtube-search"
  status = 200

[[redirects]]
  from = "/api/youtube/playlist"
  to = "/.netlify/functions/youtube-playlist"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
